# %% [markdown]
# # PS6E4 Irrigation Prediction: 14-Model GBDT Ensemble (LB 0.97876)
#
# **Best public LB: 0.97876**
#
# ## Method
#
# My approach follows the [KGMON Playbook](https://www.kaggle.com/competitions/playground-series-s6e3/writeups/1st-place-gpt5-4-gemini3-1-claudeopus4-6-kgm)
# by Chris Deotte (1st place PS6E3). The core idea: systematic feature engineering,
# diverse GBDT models, and multi-level ensembling.
#
# 1. Feature engineering with magic formula, domain interactions, 2-way target encoding
# 2. 14 GBDT models (XGBoost, LightGBM, CatBoost) with seed and feature diversity
# 3. Hill climbing ensemble with differential evolution threshold optimization
#
# All training was done on AWS SageMaker spot instances configured via the AWS CLI.
# Code was generated with Claude Code (Opus 4.6).
#
# Sections 1-2 (EDA, Features) run live. Section 3 (Training) shows code only.
# Section 4 (Ensemble) runs live using pre-computed OOF predictions from the
# companion dataset.

# %%
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from itertools import combinations

from sklearn.metrics import balanced_accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder, TargetEncoder
from scipy.optimize import differential_evolution

# %% [markdown]
# ## 1. EDA
#
# The dataset has 630K synthetic training rows generated from a 10K original dataset.
# Target is heavily imbalanced: Low 58.7%, Medium 37.9%, High 3.3%.
# Since the metric is balanced accuracy, getting the rare High class right matters
# as much as the majority Low class.

# %%
# Paths: adjust for Kaggle vs local
import os
KAGGLE_INPUT = Path("/kaggle/input")
if KAGGLE_INPUT.exists():
    DATA_DIR = KAGGLE_INPUT / "competitions" / "playground-series-s6e4"
    PRED_DIR = KAGGLE_INPUT / "datasets" / "wguesdon" / "ps6e4-irrigation-14-model-predictions"
    ORIG_PATH = PRED_DIR / "irrigation_prediction.csv"
else:
    DATA_DIR = Path("data/raw")
    PRED_DIR = Path("predictions")
    ORIG_PATH = DATA_DIR / "irrigation_prediction.csv"

train = pd.read_csv(DATA_DIR / "train.csv")
test = pd.read_csv(DATA_DIR / "test.csv")
orig = pd.read_csv(ORIG_PATH)

TARGET = "Irrigation_Need"
NUMS = [
    "Soil_pH", "Soil_Moisture", "Organic_Carbon", "Electrical_Conductivity",
    "Temperature_C", "Humidity", "Rainfall_mm", "Sunlight_Hours",
    "Wind_Speed_kmh", "Field_Area_hectare", "Previous_Irrigation_mm",
]
CATS = [
    "Soil_Type", "Crop_Type", "Crop_Growth_Stage", "Season",
    "Irrigation_Type", "Water_Source", "Mulching_Used", "Region",
]

print(f"Train: {train.shape}, Test: {test.shape}, Original: {orig.shape}")
print(f"\nTarget distribution:")
print(train[TARGET].value_counts(normalize=True).round(3))

# %%
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# Target distribution
train[TARGET].value_counts().plot.bar(
    ax=axes[0], color=["#4C72B0", "#DD8452", "#C44E52"]
)
axes[0].set_title("Target Distribution (Train)")
axes[0].set_ylabel("Count")

# Original vs Synthetic distribution
orig_dist = orig[TARGET].value_counts(normalize=True).sort_index()
train_dist = train[TARGET].value_counts(normalize=True).sort_index()
pd.DataFrame({"Original (10K)": orig_dist, "Synthetic (630K)": train_dist}).plot.bar(
    ax=axes[1]
)
axes[1].set_title("Original vs Synthetic")
axes[1].set_ylabel("Proportion")

# Numeric feature std (proxy for information content)
train[NUMS].std().sort_values().plot.barh(ax=axes[2], color="#4C72B0")
axes[2].set_title("Numeric Feature Std Dev")

plt.tight_layout()
plt.show()

# %%
# Top numeric features by class separation
fig, axes = plt.subplots(2, 3, figsize=(16, 8))
top_nums = ["Soil_Moisture", "Wind_Speed_kmh", "Temperature_C",
            "Rainfall_mm", "Humidity", "Sunlight_Hours"]

for ax, col in zip(axes.flat, top_nums):
    for label in ["Low", "Medium", "High"]:
        subset = train[train[TARGET] == label][col]
        ax.hist(subset, bins=50, alpha=0.5, label=label, density=True)
    ax.set_title(col)
    ax.legend(fontsize=8)

plt.suptitle("Top Numeric Features by Irrigation Class", fontsize=14)
plt.tight_layout()
plt.show()

# %%
# Correlation matrix
fig, ax = plt.subplots(figsize=(10, 8))
corr = train[NUMS].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap="coolwarm",
            vmin=-1, vmax=1, ax=ax)
ax.set_title("Numeric Feature Correlation")
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Key Discovery: The Magic Formula
#
# The original 10K dataset was generated by a deterministic rule that perfectly
# separates all 3 classes (balanced accuracy = 1.0). This was discovered by
# Chris Deotte in the competition forum.
#
# The synthetic generator "blurred" these boundaries by adding continuous noise
# and label flips. Our models learn to correct for this blur.

# %%
# Magic formula: achieves BA = 1.0 on the original 10K dataset
def compute_magic_score(df):
    """Compute the magic formula score from Chris Deotte's discovery."""
    high_score = (
        (df["Soil_Moisture"] < 25).astype(int) * 2
        + (df["Rainfall_mm"] < 300).astype(int) * 2
        + (df["Temperature_C"] > 30).astype(int)
        + (df["Wind_Speed_kmh"] > 10).astype(int)
    )
    low_score = (
        (df["Crop_Growth_Stage"] == "Harvest").astype(int) * 2
        + (df["Crop_Growth_Stage"] == "Sowing").astype(int) * 2
        + (df["Mulching_Used"] == "Yes").astype(int)
    )
    return high_score - low_score


orig["magic_score"] = compute_magic_score(orig)
train["magic_score"] = compute_magic_score(train)

# Verify perfect accuracy on original data
le = LabelEncoder()
le.fit(["High", "Low", "Medium"])
orig_labels = le.transform(orig[TARGET])
orig_preds = np.where(orig["magic_score"] <= 0, 1,
             np.where(orig["magic_score"] >= 4, 0, 2))
orig_ba = balanced_accuracy_score(orig_labels, orig_preds)
print(f"Magic formula on original data: BA = {orig_ba:.4f}")

# On synthetic data
train_labels = le.transform(train[TARGET])
train_preds = np.where(train["magic_score"] <= 0, 1,
              np.where(train["magic_score"] >= 4, 0, 2))
train_ba = balanced_accuracy_score(train_labels, train_preds)
print(f"Magic formula on synthetic data: BA = {train_ba:.4f}")

# Distribution of magic scores by class
fig, ax = plt.subplots(figsize=(10, 4))
for label in ["Low", "Medium", "High"]:
    subset = train[train[TARGET] == label]["magic_score"]
    ax.hist(subset, bins=range(-6, 8), alpha=0.5, label=label, density=True)
ax.set_title("Magic Score Distribution by Class")
ax.set_xlabel("Magic Score")
ax.legend()
plt.tight_layout()
plt.show()

# %% [markdown]
# ## 2. Feature Engineering (Code Reference)
#
# Our full feature pipeline generates ~300 features from the 19 base columns.
# The code below shows the complete pipeline. On Kaggle this would run for
# several minutes on the full dataset.
#
# **Feature groups:**
# - Magic formula features (15): threshold flags, composite scores, boundary distances
# - Domain interactions (13): water balance, heat stress, evapotranspiration
# - Digit extraction (11): first decimal digit per numeric column
# - Frequency encoding (8): category frequency as numeric
# - Boolean flags (3): rainfed, low moisture, high temperature
# - feature-engine transformers (41): discretisers, count-frequency encoder
# - Original dataset TE priors (19): target mean from 10K original per feature
# - 2-way interaction target encoding (118): all C(19,2) pairs, encoded inside CV

# %%
def create_features(df):
    """Full feature engineering pipeline.

    This function creates all non-CV features. The 2-way interaction target
    encoding is applied inside each CV fold to prevent leakage.
    """
    out = df.copy()

    # --- Magic formula features ---
    out["magic_soil_dry"] = (out["Soil_Moisture"] < 25).astype(np.int8)
    out["magic_rain_low"] = (out["Rainfall_mm"] < 300).astype(np.int8)
    out["magic_temp_hot"] = (out["Temperature_C"] > 30).astype(np.int8)
    out["magic_wind_high"] = (out["Wind_Speed_kmh"] > 10).astype(np.int8)
    out["magic_harvest"] = (out["Crop_Growth_Stage"] == "Harvest").astype(np.int8)
    out["magic_sowing"] = (out["Crop_Growth_Stage"] == "Sowing").astype(np.int8)
    out["magic_mulch_yes"] = (out["Mulching_Used"] == "Yes").astype(np.int8)

    out["magic_high_score"] = (
        out["magic_soil_dry"] * 2 + out["magic_rain_low"] * 2
        + out["magic_temp_hot"] + out["magic_wind_high"]
    )
    out["magic_low_score"] = (
        out["magic_harvest"] * 2 + out["magic_sowing"] * 2 + out["magic_mulch_yes"]
    )
    out["magic_score"] = out["magic_high_score"] - out["magic_low_score"]
    out["magic_dist_to_boundary"] = np.minimum(
        np.abs(out["magic_score"] - 0), np.abs(out["magic_score"] - 3)
    )
    out["margin_soil_25"] = out["Soil_Moisture"] - 25
    out["margin_rain_300"] = out["Rainfall_mm"] - 300
    out["margin_temp_30"] = out["Temperature_C"] - 30
    out["margin_wind_10"] = out["Wind_Speed_kmh"] - 10

    # --- Domain interactions ---
    out["water_balance"] = out["Rainfall_mm"] - out["Previous_Irrigation_mm"]
    out["water_per_hectare"] = (
        (out["Rainfall_mm"] + out["Previous_Irrigation_mm"])
        / (out["Field_Area_hectare"] + 0.01)
    )
    out["total_water"] = out["Rainfall_mm"] + out["Previous_Irrigation_mm"]
    out["heat_stress"] = out["Temperature_C"] * (1 - out["Humidity"] / 100)
    out["evapotranspiration"] = (
        out["Temperature_C"] * out["Sunlight_Hours"] / (out["Humidity"] + 1)
    )
    out["drying_index"] = (
        out["Sunlight_Hours"] * out["Wind_Speed_kmh"] / (out["Humidity"] + 1)
    )
    out["temp_wind"] = out["Temperature_C"] * out["Wind_Speed_kmh"]
    out["moisture_deficit"] = 50 - out["Soil_Moisture"]
    out["moisture_temp_ratio"] = out["Soil_Moisture"] / (out["Temperature_C"] + 1)
    out["irrigation_density"] = (
        out["Previous_Irrigation_mm"] / (out["Field_Area_hectare"] + 0.01)
    )

    # --- Frequency encoding ---
    for col in CATS:
        freq = out[col].value_counts(normalize=True)
        out[f"freq_{col}"] = out[col].map(freq)

    # --- Boolean flags ---
    out["is_rainfed"] = (out["Irrigation_Type"] == "Rainfed").astype(np.int8)
    out["low_moisture"] = (out["Soil_Moisture"] < 25).astype(np.int8)
    out["high_temp"] = (out["Temperature_C"] > 35).astype(np.int8)

    # --- Digit extraction ---
    for col in NUMS:
        vals = out[col].values
        frac = vals - np.floor(vals)
        out[f"{col}_d1"] = np.floor(frac * 10).astype(np.int8)

    return out


print("Feature engineering functions defined.")
print("In the full pipeline, these are applied before training.")
print("2-way interaction target encoding happens inside each CV fold.")

# %% [markdown]
# ## 3. Training (Code Reference, Not Executed)
#
# We train 14 GBDT models on AWS SageMaker using 3 algorithms, multiple seeds,
# and different feature strategies for diversity.
#
# Each model follows a 2-phase pipeline:
# 1. Optuna hyperparameter tuning (50 trials on 80/20 split)
# 2. 5-fold StratifiedKFold CV with best params, 15K estimators, 500-round early stopping
#
# Inside each fold:
# - Original 10K data appended to training set (not validation)
# - TargetEncoder fitted on train fold, applied to train/val/test
# - Balanced sample weights for class imbalance
#
# The code below shows the training loop for each model type. These are not
# executed here. The pre-computed OOF predictions are loaded in Section 4.
#
# ### 14 Models trained:
#
# | Model | Algorithm | Seed | Feature Strategy | CV |
# |-------|-----------|------|------------------|----|
# | xgb_v2 | XGBoost | 42 | all (516 features) | 0.97208 |
# | xgb_s43 | XGBoost | 43 | all | 0.97185 |
# | xgb_s44 | XGBoost | 44 | all | 0.97199 |
# | xgb_magic_core | XGBoost | 42 | magic_core (~50) | 0.97256 |
# | xgb_no_interact | XGBoost | 42 | no_interactions (~130) | 0.97262 |
# | lgb_v2 | LightGBM | 42 | all | 0.97140 |
# | lgb_s43 | LightGBM | 43 | all | 0.97131 |
# | lgb_s44 | LightGBM | 44 | all | 0.97171 |
# | cat_v2 | CatBoost | 42 | all | 0.97786 |
# | cat_s43 | CatBoost | 43 | all | 0.97802 |
# | cat_s44 | CatBoost | 44 | all | 0.97834 |
# | cat_magic42 | CatBoost | 42 | all + magic | 0.97804 |
# | cat_magic_core | CatBoost | 42 | magic_core | 0.97801 |
# | cat_magic_s45 | CatBoost | 45 | all + magic | 0.97812 |

# %%
# === TRAINING CODE (NOT EXECUTED) ===
# Shown for reproducibility. Run on a machine with GPU and 32GB+ RAM.

TRAINING_CODE = """
import xgboost as xgb
import lightgbm as lgb
from catboost import CatBoostClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import TargetEncoder
from sklearn.utils.class_weight import compute_sample_weight

N_FOLDS = 5
SEED = 42

kfold = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
oof_preds = np.zeros((len(X), 3))
test_preds = np.zeros((len(X_test), 3))

for fold, (train_idx, val_idx) in enumerate(kfold.split(X, y)):
    X_tr = X.iloc[train_idx].copy()
    y_tr = y[train_idx].copy()
    X_va = X.iloc[val_idx].copy()
    X_te = X_test.copy()

    # Inject original 10K data into training fold
    X_tr = pd.concat([X_tr, X_orig], axis=0).reset_index(drop=True)
    y_tr = np.concatenate([y_tr, y_orig])

    # In-fold target encoding on 2-way interaction columns
    encoder = TargetEncoder(target_type="multiclass", cv=5, random_state=SEED)
    X_tr[te_cols] = encoder.fit_transform(X_tr[te_cols], y_tr)
    X_va[te_cols] = encoder.transform(X_va[te_cols])
    X_te[te_cols] = encoder.transform(X_te[te_cols])

    # Balanced sample weights
    weights = compute_sample_weight(class_weight="balanced", y=y_tr)

    # --- XGBoost ---
    dtrain = xgb.DMatrix(X_tr, label=y_tr, weight=weights)
    dval = xgb.DMatrix(X_va, label=y[val_idx])
    dtest = xgb.DMatrix(X_te)

    xgb_params = {
        "objective": "multi:softprob", "num_class": 3,
        "eval_metric": "mlogloss", "eta": 0.01, "max_depth": 7,
        "subsample": 0.8, "colsample_bytree": 0.8,
        "max_bin": 1024, "tree_method": "hist", "device": "cuda",
    }
    bst = xgb.train(xgb_params, dtrain, num_boost_round=15000,
                    evals=[(dval, "val")], early_stopping_rounds=500,
                    verbose_eval=False)

    oof_preds[val_idx] = bst.predict(dval)
    test_preds += bst.predict(dtest) / N_FOLDS

    # --- LightGBM ---
    lgb_model = lgb.LGBMClassifier(
        objective="multiclass", num_class=3, is_unbalance=True,
        num_leaves=77, learning_rate=0.01, n_estimators=15000,
        subsample=0.8, colsample_bytree=0.7, verbosity=-1,
    )
    lgb_model.fit(X_tr, y_tr, eval_set=[(X_va, y[val_idx])],
                  callbacks=[lgb.early_stopping(500), lgb.log_evaluation(0)])

    # --- CatBoost ---
    cat_model = CatBoostClassifier(
        loss_function="MultiClass", classes_count=3,
        auto_class_weights="Balanced", depth=6, learning_rate=0.04,
        iterations=5000, verbose=0,
    )
    cat_model.fit(X_tr, y_tr, eval_set=(X_va, y[val_idx]),
                  early_stopping_rounds=500)
"""

print("Training code shown above (not executed).")
print("Pre-computed OOF predictions are loaded in Section 4.")

# %% [markdown]
# ## 4. Ensemble: Hill Climbing + Differential Evolution Thresholds
#
# This section runs live. We load the 14 pre-computed OOF and test predictions
# from our companion Kaggle dataset, then:
# 1. Hill climbing to find optimal blend weights
# 2. Differential evolution to optimize class-specific thresholds for balanced accuracy

# %%
# Load pre-computed predictions
MODEL_NAMES = [
    "xgb_v2", "xgb_s43", "xgb_s44", "xgb_magic_core", "xgb_no_interact",
    "lgb_v2", "lgb_s43", "lgb_s44",
    "cat_v2", "cat_s43", "cat_s44",
    "cat_magic42", "cat_magic_core", "cat_magic_s45",
]

oof_dict = {}
pred_dict = {}
for name in MODEL_NAMES:
    oof_dict[name] = np.load(PRED_DIR / f"oof_{name}.npy")
    pred_dict[name] = np.load(PRED_DIR / f"pred_{name}.npy")

print(f"Loaded {len(MODEL_NAMES)} models")
print(f"OOF shape: {oof_dict[MODEL_NAMES[0]].shape}")
print(f"Test pred shape: {pred_dict[MODEL_NAMES[0]].shape}")

# Load ground truth labels
le = LabelEncoder()
le.fit(["High", "Low", "Medium"])
y = le.transform(train[TARGET])
test_ids = test["id"]

# Individual model CV scores
print("\nIndividual model CV scores:")
for name in MODEL_NAMES:
    score = balanced_accuracy_score(y, oof_dict[name].argmax(axis=1))
    print(f"  {name:20s}  CV = {score:.5f}")

# %%
# Model prediction correlation (diversity check)
corr_data = {}
for name in MODEL_NAMES:
    corr_data[name] = oof_dict[name].argmax(axis=1)
corr_df = pd.DataFrame(corr_data)

fig, ax = plt.subplots(figsize=(12, 10))
mask = np.triu(np.ones_like(corr_df.corr(), dtype=bool))
sns.heatmap(corr_df.corr(), mask=mask, annot=True, fmt=".3f", cmap="coolwarm",
            vmin=0.8, vmax=1.0, ax=ax)
ax.set_title("Model Prediction Correlation (lower = more diverse)")
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Hill Climbing Ensemble
#
# Greedy weight optimization: perturb weights randomly, keep changes that
# improve balanced accuracy on OOF predictions.

# %%
def hill_climbing_ensemble(oof_dict, y_true, n_iterations=5000, seed=42):
    """Find optimal blend weights via stochastic hill climbing."""
    rng = np.random.RandomState(seed)
    names = list(oof_dict.keys())
    oofs = [oof_dict[n] for n in names]
    n_models = len(oofs)

    weights = np.ones(n_models) / n_models
    blend = sum(w * o for w, o in zip(weights, oofs))
    best_score = balanced_accuracy_score(y_true, blend.argmax(axis=1))
    best_weights = weights.copy()

    for i in range(n_iterations):
        lr = max(0.005, 0.1 * (1 - i / n_iterations))
        new_weights = best_weights + rng.randn(n_models) * lr
        new_weights = np.clip(new_weights, 0, None)
        new_weights /= new_weights.sum()

        blend = sum(w * o for w, o in zip(new_weights, oofs))
        score = balanced_accuracy_score(y_true, blend.argmax(axis=1))

        if score > best_score:
            best_score = score
            best_weights = new_weights.copy()

    return {n: float(w) for n, w in zip(names, best_weights)}, best_score


weights, ensemble_cv = hill_climbing_ensemble(oof_dict, y)
print(f"Hill Climbing Ensemble CV: {ensemble_cv:.5f}")
print(f"\nModel weights:")
for name, w in sorted(weights.items(), key=lambda x: -x[1]):
    if w > 0.01:
        print(f"  {name:20s}  {w:.4f}")

# %%
# Visualize weights
fig, ax = plt.subplots(figsize=(10, 5))
sorted_weights = sorted(weights.items(), key=lambda x: x[1], reverse=True)
names_sorted = [n for n, _ in sorted_weights]
vals_sorted = [v for _, v in sorted_weights]
colors = ["#C44E52" if "cat" in n else "#4C72B0" if "xgb" in n else "#DD8452"
          for n in names_sorted]
ax.barh(names_sorted, vals_sorted, color=colors)
ax.set_title("Ensemble Weights (Hill Climbing)")
ax.set_xlabel("Weight")
plt.tight_layout()
plt.show()

# %% [markdown]
# ### Differential Evolution Threshold Optimization
#
# Balanced accuracy = average recall across classes. By applying per-class
# multipliers to the blended probabilities before argmax, we can shift the
# decision boundaries to maximize this metric.
#
# Differential evolution is a global optimizer that avoids the local optima
# that Nelder-Mead can get stuck in.

# %%
# Create blended OOF and test predictions
oof_blend = sum(weights[n] * oof_dict[n] for n in MODEL_NAMES)
test_blend = sum(weights[n] * pred_dict[n] for n in MODEL_NAMES)

baseline_cv = balanced_accuracy_score(y, oof_blend.argmax(axis=1))
print(f"Ensemble CV (no thresholds): {baseline_cv:.5f}")


def neg_balanced_accuracy(thresholds):
    """Objective for differential evolution: minimize negative BA."""
    adjusted = oof_blend * thresholds
    return -balanced_accuracy_score(y, adjusted.argmax(axis=1))


result = differential_evolution(
    neg_balanced_accuracy,
    bounds=[(0.5, 3.0), (0.5, 3.0), (0.5, 3.0)],
    seed=42,
    maxiter=1000,
    tol=1e-8,
)

best_thresholds = result.x
optimized_cv = -result.fun
print(f"Optimized thresholds: {best_thresholds}")
print(f"Ensemble CV (with thresholds): {optimized_cv:.5f}")
print(f"Gain from threshold optimization: +{optimized_cv - baseline_cv:.5f}")

# %%
# Confusion matrix
optimized_preds = (oof_blend * best_thresholds).argmax(axis=1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

cm = confusion_matrix(y, optimized_preds)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[0],
            xticklabels=["High", "Low", "Medium"],
            yticklabels=["High", "Low", "Medium"])
axes[0].set_title(f"Confusion Matrix (CV={optimized_cv:.5f})")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("True")

# Per-class recall
class_names = ["High", "Low", "Medium"]
recalls = []
for cls in range(3):
    mask = y == cls
    recall = (optimized_preds[mask] == cls).mean()
    recalls.append(recall)
    print(f"  {class_names[cls]:8s} recall = {recall:.4f} (n={mask.sum()})")

axes[1].bar(class_names, recalls, color=["#C44E52", "#4C72B0", "#DD8452"])
axes[1].set_title("Per-Class Recall")
axes[1].set_ylabel("Recall")
axes[1].set_ylim(0.9, 1.0)

plt.tight_layout()
plt.show()

# %% [markdown]
# ## 5. Submission

# %%
final_test_probs = test_blend * best_thresholds
final_test_classes = final_test_probs.argmax(axis=1)

labels = le.inverse_transform(final_test_classes)
submission = pd.DataFrame({"id": test_ids, TARGET: labels})
submission.to_csv("submission.csv", index=False)

print(f"Submission saved: submission.csv ({len(submission)} rows)")
print(f"\nPredicted distribution:")
print(submission[TARGET].value_counts())

# %% [markdown]
# ## Summary
#
# | Component | Details |
# |-----------|---------|
# | Models | 14 GBDT models (5 XGBoost, 3 LightGBM, 6 CatBoost) |
# | Diversity | 4 seeds (42-45) + 3 feature strategies (all, magic_core, no_interactions) |
# | Features | ~300 features: magic formula, domain interactions, 2-way TE, digit extraction |
# | Ensemble | Hill climbing weight optimization (5000 iterations) |
# | Thresholds | Differential evolution on per-class probability multipliers |
# | Infrastructure | AWS SageMaker spot instances (GPU for XGB/CatBoost, CPU for LightGBM) |
# | Best CV | 0.97930 |
# | Best LB | 0.97876 |
