#!/usr/bin/env python
"""Showcase v2 training: feature-engine + 4-model ensemble.

Trains XGBoost, LightGBM, CatBoost, and RealMLP with fixed hyperparameters
(no Optuna). Uses feature-engine for feature engineering and 5-fold
StratifiedKFold CV. Original data injection + in-fold target encoding.

Outputs per model:
    {output_dir}/oof_{name}_sc2.npy   (N, 3) OOF probabilities
    {output_dir}/pred_{name}_sc2.npy  (N_test, 3) test probabilities
    {sub_dir}/sub_{name}_sc2.csv      Individual submission CSV

Works locally or on SageMaker (detects SM_CHANNEL_TRAINING env var).

Usage:
    uv run python Playground_Series/PS6E4/scripts/showcase_v2_train.py
    uv run python Playground_Series/PS6E4/scripts/showcase_v2_train.py --test
"""

import gc
import os
import sys
import argparse
import warnings
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import balanced_accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_sample_weight

# feature-engine
from feature_engine.encoding import CountFrequencyEncoder, MeanEncoder
from feature_engine.creation import RelativeFeatures, MathFeatures
from feature_engine.discretisation import (
    EqualFrequencyDiscretiser,
    EqualWidthDiscretiser,
    DecisionTreeDiscretiser,
)

warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TARGET = "Irrigation_Need"
LABEL_ORDER = ["High", "Low", "Medium"]  # LabelEncoder alphabetical
SEED = 42

NUMERIC_COLS = [
    "Soil_pH", "Soil_Moisture", "Organic_Carbon", "Electrical_Conductivity",
    "Temperature_C", "Humidity", "Rainfall_mm", "Sunlight_Hours",
    "Wind_Speed_kmh", "Field_Area_hectare", "Previous_Irrigation_mm",
]

CAT_COLS = [
    "Soil_Type", "Crop_Type", "Crop_Growth_Stage", "Season",
    "Irrigation_Type", "Water_Source", "Mulching_Used", "Region",
]

# Key numerics for binning
BIN_COLS = [
    "Soil_Moisture", "Temperature_C", "Rainfall_mm",
    "Wind_Speed_kmh", "Humidity", "Previous_Irrigation_mm",
]

# Top interaction pairs from EDA
INTERACTION_PAIRS = [
    ("Crop_Growth_Stage", "Crop_Type"),
    ("Crop_Growth_Stage", "Irrigation_Type"),
    ("Irrigation_Type", "Season"),
    ("Crop_Type", "Season"),
    ("Mulching_Used", "Irrigation_Type"),
    ("Soil_Type", "Crop_Type"),
    ("Region", "Season"),
    ("Irrigation_Type", "Water_Source"),
]


# =========================================================================
# Feature engineering
# =========================================================================

def add_magic_features(df):
    """Add magic formula features from the original dataset rule.

    The original 10K dataset was generated by a deterministic formula
    involving threshold comparisons. These features expose that structure
    to the model.

    Args:
        df: DataFrame with raw feature columns.

    Returns:
        DataFrame with magic features appended.
    """
    df = df.copy()
    df["magic_soil_dry"] = (df["Soil_Moisture"] < 25).astype(np.int8)
    df["magic_rain_low"] = (df["Rainfall_mm"] < 300).astype(np.int8)
    df["magic_temp_hot"] = (df["Temperature_C"] > 30).astype(np.int8)
    df["magic_wind_high"] = (df["Wind_Speed_kmh"] > 10).astype(np.int8)
    df["magic_harvest"] = (df["Crop_Growth_Stage"] == "Harvest").astype(np.int8)
    df["magic_sowing"] = (df["Crop_Growth_Stage"] == "Sowing").astype(np.int8)
    df["magic_mulch_yes"] = (df["Mulching_Used"] == "Yes").astype(np.int8)

    df["magic_high_score"] = (
        df["magic_soil_dry"] * 2 + df["magic_rain_low"] * 2
        + df["magic_temp_hot"] + df["magic_wind_high"]
    )
    df["magic_low_score"] = (
        df["magic_harvest"] * 2 + df["magic_sowing"] * 2 + df["magic_mulch_yes"]
    )
    df["magic_score"] = df["magic_high_score"] - df["magic_low_score"]

    df["magic_soil_margin"] = 25 - df["Soil_Moisture"]
    df["magic_rain_margin"] = 300 - df["Rainfall_mm"]
    df["magic_temp_margin"] = df["Temperature_C"] - 30
    df["magic_wind_margin"] = df["Wind_Speed_kmh"] - 10
    df["magic_boundary_dist"] = df[
        ["magic_soil_margin", "magic_rain_margin",
         "magic_temp_margin", "magic_wind_margin"]
    ].abs().min(axis=1)
    return df


def add_domain_features(df):
    """Add domain-knowledge interaction features.

    Physics-inspired features for water balance, heat stress,
    evapotranspiration, and soil efficiency.

    Args:
        df: DataFrame with raw feature columns.

    Returns:
        DataFrame with domain features appended.
    """
    df = df.copy()
    df["water_balance"] = df["Rainfall_mm"] - df["Previous_Irrigation_mm"]
    df["heat_stress"] = df["Temperature_C"] * (100 - df["Humidity"]) / 100
    df["ET_proxy"] = (
        df["Temperature_C"] * df["Wind_Speed_kmh"]
        * (100 - df["Humidity"]) / 100
    )
    df["drying_index"] = (
        df["Wind_Speed_kmh"] * df["Temperature_C"]
        / df["Humidity"].clip(lower=1)
    )
    df["moisture_deficit"] = df["Soil_Moisture"] - df["Rainfall_mm"] / 10
    df["water_per_hectare"] = (
        (df["Rainfall_mm"] + df["Previous_Irrigation_mm"])
        / (df["Field_Area_hectare"] + 0.01)
    )
    df["moisture_temp_ratio"] = df["Soil_Moisture"] / (df["Temperature_C"] + 1)
    return df


def label_encode_categoricals(train, test, orig):
    """Label-encode categorical columns fitted on combined data.

    Args:
        train: Training DataFrame.
        test: Test DataFrame.
        orig: Original 10K DataFrame.

    Returns:
        Tuple of (train, test, orig) with _le columns added.
    """
    combined = pd.concat(
        [train[CAT_COLS], test[CAT_COLS], orig[CAT_COLS]], ignore_index=True,
    )
    for col in CAT_COLS:
        le = LabelEncoder()
        le.fit(combined[col].astype(str))
        for df in [train, test, orig]:
            df[f"{col}_le"] = le.transform(df[col].astype(str))
    return train, test, orig


def apply_feature_engine_static(train, test):
    """Apply feature-engine transformers that do not use the target.

    Fit on train, transform both train and test.

    Uses:
        CountFrequencyEncoder: category frequency as numeric.
        EqualFrequencyDiscretiser: quantile binning (10 bins).
        EqualWidthDiscretiser: fixed-width binning (15 bins).
        RelativeFeatures: pairwise ratios and products.
        MathFeatures: aggregate statistics of feature groups.

    Args:
        train: Training DataFrame.
        test: Test DataFrame.

    Returns:
        Tuple of (train, test, list of new column names).
    """
    new_cols = []

    # 1. Frequency encoding for categoricals
    cfe = CountFrequencyEncoder(
        encoding_method="frequency", variables=CAT_COLS, missing_values="ignore",
    )
    cfe.fit(train[CAT_COLS])
    cfe_train = cfe.transform(train[CAT_COLS].copy())
    cfe_test = cfe.transform(test[CAT_COLS].copy())
    for col in CAT_COLS:
        name = f"cfe_{col}"
        train[name] = cfe_train[col].values
        test[name] = cfe_test[col].values
        new_cols.append(name)

    # 2. Equal-frequency binning (quantile, 10 bins)
    efd = EqualFrequencyDiscretiser(q=10, variables=BIN_COLS, return_boundaries=False)
    efd.fit(train[BIN_COLS])
    efd_train = efd.transform(train[BIN_COLS].copy())
    efd_test = efd.transform(test[BIN_COLS].copy())
    for col in BIN_COLS:
        name = f"efd10_{col}"
        train[name] = efd_train[col].values
        test[name] = efd_test[col].values
        new_cols.append(name)

    # 3. Equal-width binning (15 bins)
    ewd = EqualWidthDiscretiser(bins=15, variables=BIN_COLS, return_boundaries=False)
    ewd.fit(train[BIN_COLS])
    ewd_train = ewd.transform(train[BIN_COLS].copy())
    ewd_test = ewd.transform(test[BIN_COLS].copy())
    for col in BIN_COLS:
        name = f"ewd15_{col}"
        train[name] = ewd_train[col].values
        test[name] = ewd_test[col].values
        new_cols.append(name)

    # 4. Relative features: pairwise differences and products
    rel_vars = ["Soil_Moisture", "Temperature_C", "Humidity"]
    rel_refs = ["Wind_Speed_kmh", "Rainfall_mm"]
    rel_input_cols = rel_vars + rel_refs
    rel_tf = RelativeFeatures(
        variables=rel_vars, reference=rel_refs, func=["sub", "mul"],
    )
    rel_tf.fit(train[rel_input_cols])
    rel_train = rel_tf.transform(train[rel_input_cols].copy())
    rel_test = rel_tf.transform(test[rel_input_cols].copy())
    rel_new = [c for c in rel_train.columns if c not in rel_input_cols]
    for col in rel_new:
        train[col] = rel_train[col].values
        test[col] = rel_test[col].values
    new_cols.extend(rel_new)

    # 5. Aggregate math features: mean and std of top features
    math_vars = ["Soil_Moisture", "Temperature_C", "Humidity", "Wind_Speed_kmh"]
    math_tf = MathFeatures(variables=math_vars, func=["mean", "std"], missing_values="ignore")
    math_tf.fit(train[math_vars])
    math_train = math_tf.transform(train[math_vars].copy())
    math_test = math_tf.transform(test[math_vars].copy())
    math_new = [c for c in math_train.columns if c not in math_vars]
    for col in math_new:
        train[col] = math_train[col].values
        test[col] = math_test[col].values
    new_cols.extend(math_new)

    return train, test, new_cols


def add_original_te_priors(train, test, orig):
    """Add target encoding priors from the original 10K dataset.

    For each categorical column, compute mean target per category from
    the original data. Leakage-free because the original dataset is
    independent of the synthetic split.

    Args:
        train: Training DataFrame.
        test: Test DataFrame.
        orig: Original DataFrame with TARGET column.

    Returns:
        Tuple of (train, test, list of new column names).
    """
    le = LabelEncoder()
    le.fit(LABEL_ORDER)
    orig_y = le.transform(orig[TARGET])
    global_mean = orig_y.mean()

    prior_cols = []
    for col in CAT_COLS:
        name = f"orig_prior_{col}"
        te_map = pd.Series(orig_y).groupby(orig[col]).mean()
        train[name] = train[col].map(te_map).fillna(global_mean).astype(np.float32)
        test[name] = test[col].map(te_map).fillna(global_mean).astype(np.float32)
        prior_cols.append(name)

    return train, test, prior_cols


def create_2way_interactions(train, test):
    """Create 2-way categorical interaction columns as factorized integers.

    Generates all C(19,2) = 171 pairs from numeric + categorical columns.
    Drops high-cardinality pairs where more than 50% of values are unique.

    Args:
        train: Training DataFrame.
        test: Test DataFrame.

    Returns:
        Tuple of (train, test, list of interaction column names).
    """
    all_cols = NUMERIC_COLS + CAT_COLS
    interaction_cols = []

    for col_a, col_b in combinations(all_cols, 2):
        name = f"{col_a}-{col_b}"
        combined = pd.concat([
            train[col_a].astype(str) + "_" + train[col_b].astype(str),
            test[col_a].astype(str) + "_" + test[col_b].astype(str),
        ], ignore_index=True)
        encoded, _ = combined.factorize()
        if pd.Series(encoded).nunique() > len(combined) // 2:
            continue
        train[name] = encoded[:len(train)]
        test[name] = encoded[len(train):]
        interaction_cols.append(name)

    return train, test, interaction_cols


def apply_fold_features(X_train, X_val, X_test, y_train):
    """Apply target-dependent feature-engine transformers inside a CV fold.

    DecisionTreeDiscretiser: supervised binning using a shallow decision tree.
    MeanEncoder: target encoding for bigram interaction columns.

    Fit on training fold only, transform val and test.

    Args:
        X_train: Training fold features.
        X_val: Validation fold features.
        X_test: Test features.
        y_train: Training fold target (numeric).

    Returns:
        Tuple of (X_train, X_val, X_test) with fold features added.
    """
    y_series = pd.Series(y_train, index=X_train.index)

    # 1. Decision tree supervised binning
    bin_cols_present = [c for c in BIN_COLS if c in X_train.columns]
    dtd = DecisionTreeDiscretiser(
        variables=bin_cols_present,
        regression=False,
        scoring="balanced_accuracy",
        cv=3,
        param_grid={"max_depth": [2, 3]},
    )
    dtd.fit(X_train[bin_cols_present], y_series)
    dtd_train = dtd.transform(X_train[bin_cols_present].copy())
    dtd_val = dtd.transform(X_val[bin_cols_present].copy())
    dtd_test = dtd.transform(X_test[bin_cols_present].copy())
    for col in bin_cols_present:
        name = f"dtd_{col}"
        X_train[name] = dtd_train[col].values
        X_val[name] = dtd_val[col].values
        X_test[name] = dtd_test[col].values

    # 2. Mean target encoding for interaction pairs
    # Use label-encoded versions since original categoricals may not be present
    interaction_present = []
    for c1, c2 in INTERACTION_PAIRS:
        le_c1 = f"{c1}_le" if f"{c1}_le" in X_train.columns else c1
        le_c2 = f"{c2}_le" if f"{c2}_le" in X_train.columns else c2
        name = f"bigram_{c1}_{c2}"
        for df in [X_train, X_val, X_test]:
            df[name] = df[le_c1].astype(str) + "_" + df[le_c2].astype(str)
        interaction_present.append(name)

    global_mean = y_train.mean()
    for col in interaction_present:
        te_map = y_series.groupby(X_train[col]).mean()
        X_train[f"{col}_te"] = X_train[col].map(te_map).fillna(global_mean)
        X_val[f"{col}_te"] = X_val[col].map(te_map).fillna(global_mean)
        X_test[f"{col}_te"] = X_test[col].map(te_map).fillna(global_mean)

    # Drop the raw string bigram columns
    for col in interaction_present:
        X_train.drop(columns=[col], inplace=True)
        X_val.drop(columns=[col], inplace=True)
        X_test.drop(columns=[col], inplace=True)

    return X_train, X_val, X_test


def build_all_static_features(train, test, orig):
    """Full static feature engineering pipeline.

    Args:
        train: Training DataFrame.
        test: Test DataFrame.
        orig: Original 10K DataFrame.

    Returns:
        Tuple of (train, test, orig, feature_cols, interaction_cols).
    """
    print("Feature engineering: magic formula...")
    train = add_magic_features(train)
    test = add_magic_features(test)
    orig = add_magic_features(orig)

    print("Feature engineering: domain features...")
    train = add_domain_features(train)
    test = add_domain_features(test)
    orig = add_domain_features(orig)

    print("Feature engineering: label encoding...")
    train, test, orig = label_encode_categoricals(train, test, orig)

    print("Feature engineering: feature-engine (static)...")
    train, test, fe_cols = apply_feature_engine_static(train, test)
    print(f"  Feature-engine added {len(fe_cols)} columns")

    print("Feature engineering: original TE priors...")
    train, test, prior_cols = add_original_te_priors(train, test, orig)
    print(f"  Original priors: {len(prior_cols)} columns")

    print("Feature engineering: 2-way interactions...")
    train, test, interaction_cols = create_2way_interactions(train, test)
    print(f"  Interaction columns: {len(interaction_cols)}")

    # Also apply static features to orig for injection
    # Fill missing columns with 0
    for col in train.columns:
        if col not in orig.columns:
            orig[col] = 0

    exclude = {"id", TARGET} | set(CAT_COLS)
    feature_cols = [c for c in train.columns if c not in exclude]
    print(f"Total features: {len(feature_cols)}")

    return train, test, orig, feature_cols, interaction_cols


# =========================================================================
# Model training
# =========================================================================

def train_xgb_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop):
    """Train XGBoost on one fold with balanced weights.

    Args:
        X_tr: Training features.
        y_tr: Training target.
        X_va: Validation features.
        y_va: Validation target.
        n_estimators: Max boosting rounds.
        early_stop: Early stopping patience.

    Returns:
        Fitted XGBClassifier.
    """
    from xgboost import XGBClassifier

    has_gpu = __import__("shutil").which("nvidia-smi") is not None
    model = XGBClassifier(
        objective="multi:softprob",
        num_class=3,
        eval_metric="mlogloss",
        max_depth=6,
        learning_rate=0.01,
        n_estimators=n_estimators,
        subsample=0.8,
        colsample_bytree=0.8,
        max_bin=1024,
        tree_method="hist",
        device="cuda" if has_gpu else "cpu",
        random_state=SEED,
        n_jobs=-1,
        verbosity=0,
    )
    weights = compute_sample_weight("balanced", y_tr)
    model.fit(
        X_tr, y_tr,
        eval_set=[(X_va, y_va)],
        sample_weight=weights,
        verbose=False,
    )
    return model


def train_lgb_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop):
    """Train LightGBM on one fold with is_unbalance.

    Args:
        X_tr: Training features.
        y_tr: Training target.
        X_va: Validation features.
        y_va: Validation target.
        n_estimators: Max boosting rounds.
        early_stop: Early stopping patience.

    Returns:
        Fitted LGBMClassifier.
    """
    import lightgbm as lgb

    model = lgb.LGBMClassifier(
        objective="multiclass",
        num_class=3,
        num_leaves=77,
        learning_rate=0.01,
        n_estimators=n_estimators,
        subsample=0.8,
        colsample_bytree=0.7,
        reg_lambda=7.0,
        is_unbalance=True,
        random_state=SEED,
        n_jobs=-1,
        verbosity=-1,
    )
    model.fit(
        X_tr, y_tr,
        eval_set=[(X_va, y_va)],
        callbacks=[
            lgb.early_stopping(early_stop, verbose=False),
            lgb.log_evaluation(0),
        ],
    )
    return model


def train_cat_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop):
    """Train CatBoost on one fold with balanced weights.

    Args:
        X_tr: Training features.
        y_tr: Training target.
        X_va: Validation features.
        y_va: Validation target.
        n_estimators: Max boosting rounds.
        early_stop: Early stopping patience.

    Returns:
        Fitted CatBoostClassifier.
    """
    from catboost import CatBoostClassifier

    has_gpu = __import__("shutil").which("nvidia-smi") is not None
    model = CatBoostClassifier(
        loss_function="MultiClass",
        classes_count=3,
        auto_class_weights="Balanced",
        depth=6,
        learning_rate=0.04,
        iterations=n_estimators,
        l2_leaf_reg=0.5,
        random_strength=8.0,
        bagging_temperature=0.4,
        task_type="GPU" if has_gpu else "CPU",
        random_seed=SEED,
        verbose=0,
    )
    model.fit(X_tr, y_tr, eval_set=(X_va, y_va), early_stopping_rounds=early_stop)
    return model


def train_realmlp_fold(X_tr, y_tr, X_va, y_va):
    """Train RealMLP on one fold using pytabkit.

    Uses Mahog's RealMLP approach with internal ensembling (n_ens=5).

    Args:
        X_tr: Training features (numpy or DataFrame).
        y_tr: Training target.
        X_va: Validation features.
        y_va: Validation target.

    Returns:
        Fitted RealMLP_TD_Classifier.
    """
    from pytabkit.models.sklearn.sklearn_interfaces import RealMLP_TD_Classifier

    model = RealMLP_TD_Classifier(
        n_cv=1,
        n_refit=0,
        n_ens=5,
        device="cuda",
        verbosity=0,
    )
    model.fit(X_tr.values if hasattr(X_tr, "values") else X_tr, y_tr)
    return model


def run_model_cv(model_name, train_fn, X, y, X_test, X_orig, y_orig,
                 feature_cols, interaction_cols, n_folds, n_estimators,
                 early_stop, output_dir, sub_dir, test_ids, le):
    """Run full CV for one model, save predictions and submission.

    Args:
        model_name: Short name for files.
        train_fn: Callable(X_tr, y_tr, X_va, y_va) -> fitted model.
        X: Full training DataFrame.
        y: Full training target array.
        X_test: Full test DataFrame.
        X_orig: Original data DataFrame for injection.
        y_orig: Original data target array.
        feature_cols: List of feature column names.
        interaction_cols: 2-way interaction columns for in-fold TE.
        n_folds: Number of CV folds.
        n_estimators: Max estimators for GBDT models.
        early_stop: Early stopping rounds.
        output_dir: Path for .npy files.
        sub_dir: Path for submission CSVs.
        test_ids: Test set IDs for submission.
        le: Fitted LabelEncoder.

    Returns:
        Tuple of (oof_preds, test_preds, cv_score).
    """
    kfold = StratifiedKFold(n_splits=n_folds, shuffle=True, random_state=SEED)
    oof_preds = np.zeros((len(X), 3))
    test_preds = np.zeros((len(X_test), 3))
    fold_scores = []

    print(f"\n{'=' * 50}")
    print(f"  Training {model_name} ({n_folds}-fold CV)")
    print(f"{'=' * 50}")

    for fold, (train_idx, val_idx) in enumerate(kfold.split(X, y)):
        X_tr = X.iloc[train_idx][feature_cols].copy()
        y_tr = y[train_idx].copy()
        X_va = X.iloc[val_idx][feature_cols].copy()
        X_te = X_test[feature_cols].copy()

        # Inject original data into training fold
        X_orig_fold = X_orig[feature_cols].copy()
        X_tr = pd.concat([X_tr, X_orig_fold], axis=0).reset_index(drop=True)
        y_tr = np.concatenate([y_tr, y_orig])

        # In-fold target encoding and supervised binning
        X_tr, X_va, X_te = apply_fold_features(X_tr, X_va, X_te, y_tr)

        # Get final feature list after fold features
        fold_features = [c for c in X_tr.columns if c not in (set(CAT_COLS) | {"id", TARGET})]

        # Train
        model = train_fn(X_tr[fold_features], y_tr, X_va[fold_features], y[val_idx])

        # Predict
        if hasattr(model, "predict_proba"):
            oof_preds[val_idx] = model.predict_proba(X_va[fold_features])
            test_preds += model.predict_proba(X_te[fold_features]) / n_folds
        else:
            # pytabkit models
            va_vals = X_va[fold_features].values if hasattr(X_va, "values") else X_va[fold_features]
            te_vals = X_te[fold_features].values if hasattr(X_te, "values") else X_te[fold_features]
            oof_preds[val_idx] = model.predict_proba(va_vals)
            test_preds += model.predict_proba(te_vals) / n_folds

        score = balanced_accuracy_score(y[val_idx], oof_preds[val_idx].argmax(axis=1))
        fold_scores.append(score)
        print(f"  Fold {fold + 1}/{n_folds}: {score:.5f}")

        del model
        gc.collect()

    cv_score = balanced_accuracy_score(y, oof_preds.argmax(axis=1))
    print(f"  {model_name} CV: {cv_score:.5f} (+/- {np.std(fold_scores):.5f})")

    # Save predictions
    suffix = "_sc2"
    np.save(output_dir / f"oof_{model_name}{suffix}.npy", oof_preds)
    np.save(output_dir / f"pred_{model_name}{suffix}.npy", test_preds)

    # Save individual submission
    test_labels = le.inverse_transform(test_preds.argmax(axis=1))
    sub = pd.DataFrame({"id": test_ids, TARGET: test_labels})
    sub_path = sub_dir / f"sub_{model_name}{suffix}.csv"
    sub.to_csv(sub_path, index=False)
    print(f"  Saved: {sub_path}")

    return oof_preds, test_preds, cv_score


# =========================================================================
# Main
# =========================================================================

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Showcase v2: 4-model training")
    parser.add_argument("--test", action="store_true",
                        help="Fast test mode: 10%% subsample, 3 folds, 500 estimators")
    parser.add_argument("--skip-realmlp", action="store_true",
                        help="Skip RealMLP training (requires pytabkit + GPU)")
    parser.add_argument("--models", default="xgb,lgb,cat,realmlp",
                        help="Comma-separated model list (default: xgb,lgb,cat,realmlp)")
    args, _ = parser.parse_known_args()
    return args


def run():
    """Main training entry point."""
    args = parse_args()

    # Detect SageMaker or local paths
    sm_training = os.environ.get("SM_CHANNEL_TRAINING")
    sm_model_dir = os.environ.get("SM_MODEL_DIR")

    if sm_training:
        data_dir = Path(sm_training)
        output_dir = Path(sm_model_dir or "/opt/ml/model")
        sub_dir = output_dir
    else:
        script_dir = Path(__file__).resolve().parent.parent
        data_dir = script_dir / "data" / "raw"
        output_dir = script_dir / "predictions"
        sub_dir = script_dir / "submissions"

    output_dir.mkdir(parents=True, exist_ok=True)
    sub_dir.mkdir(parents=True, exist_ok=True)

    # Config
    test_mode = args.test
    n_folds = 3 if test_mode else 5
    n_estimators = 500 if test_mode else 15000
    early_stop = 50 if test_mode else 500
    models_to_train = [m.strip() for m in args.models.split(",")]

    if test_mode:
        print("=" * 50)
        print("  TEST MODE: subsampled data, fast training")
        print("=" * 50)

    # Load data
    print("Loading data...")
    train = pd.read_csv(data_dir / "train.csv")
    test = pd.read_csv(data_dir / "test.csv")
    orig = pd.read_csv(data_dir / "irrigation_prediction.csv")
    test_ids = test["id"]
    print(f"  Train: {train.shape}, Test: {test.shape}, Original: {orig.shape}")

    # Encode target
    le = LabelEncoder()
    le.fit(LABEL_ORDER)
    y = le.transform(train[TARGET])
    y_orig = le.transform(orig[TARGET])

    # Subsample in test mode
    if test_mode:
        from sklearn.model_selection import train_test_split
        train, _ = train_test_split(
            train, train_size=0.1, stratify=y, random_state=SEED,
        )
        y = le.transform(train[TARGET])
        test = test.sample(frac=0.1, random_state=SEED).reset_index(drop=True)
        test_ids = test["id"]
        train = train.reset_index(drop=True)
        print(f"  [TEST] Subsampled: Train={train.shape}, Test={test.shape}")

    # Feature engineering
    train, test, orig, feature_cols, interaction_cols = build_all_static_features(
        train, test, orig,
    )

    X = train
    X_test = test
    X_orig = orig

    # Train models
    results = {}

    if "xgb" in models_to_train:
        def xgb_fn(X_tr, y_tr, X_va, y_va):
            return train_xgb_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop)

        oof, pred, cv = run_model_cv(
            "xgb", xgb_fn, X, y, X_test, X_orig, y_orig,
            feature_cols, interaction_cols, n_folds, n_estimators, early_stop,
            output_dir, sub_dir, test_ids, le,
        )
        results["xgb"] = cv

    if "lgb" in models_to_train:
        def lgb_fn(X_tr, y_tr, X_va, y_va):
            return train_lgb_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop)

        oof, pred, cv = run_model_cv(
            "lgb", lgb_fn, X, y, X_test, X_orig, y_orig,
            feature_cols, interaction_cols, n_folds, n_estimators, early_stop,
            output_dir, sub_dir, test_ids, le,
        )
        results["lgb"] = cv

    if "cat" in models_to_train:
        def cat_fn(X_tr, y_tr, X_va, y_va):
            return train_cat_fold(X_tr, y_tr, X_va, y_va, n_estimators, early_stop)

        oof, pred, cv = run_model_cv(
            "cat", cat_fn, X, y, X_test, X_orig, y_orig,
            feature_cols, interaction_cols, n_folds, n_estimators, early_stop,
            output_dir, sub_dir, test_ids, le,
        )
        results["cat"] = cv

    if "realmlp" in models_to_train and not args.skip_realmlp:
        try:
            from pytabkit.models.sklearn.sklearn_interfaces import RealMLP_TD_Classifier  # noqa: F401

            oof, pred, cv = run_model_cv(
                "realmlp", train_realmlp_fold, X, y, X_test, X_orig, y_orig,
                feature_cols, interaction_cols, n_folds, n_estimators, early_stop,
                output_dir, sub_dir, test_ids, le,
            )
            results["realmlp"] = cv
        except ImportError:
            print("WARNING: pytabkit not installed, skipping RealMLP")

    # Summary
    print(f"\n{'=' * 50}")
    print("  TRAINING COMPLETE")
    print(f"{'=' * 50}")
    for name, cv in results.items():
        print(f"  {name:10s}  CV = {cv:.5f}")
    print(f"\n  Predictions saved to: {output_dir}")
    print(f"  Submissions saved to: {sub_dir}")


if __name__ == "__main__":
    run()
